services:
  - type: web
    name: labmath-admin
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: labmathdb
          property: connectionString
      - key: ADMIN_EMAIL
        value: admin@labmath.com
      - key: PYTHON_VERSION
        value: 3.11.0  # Forcer Python 3.11 qui est plus stable
    healthCheckPath: /health
    autoDeploy: true
    
    databases:
      - name: labmathdb
        databaseName: labmath_admin
        plan: free